replicaCount: 1

image:
  repository: resumescreener-ai-screener-service
  pullPolicy: IfNotPresent
  tag: "sha-aac880d"

service:
  type: ClusterIP
  port: 8003

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  REDIS_HOST: redis-master
  REDIS_PORT: 6379
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: resume_screener
  POSTGRES_USER: screener
  POSTGRES_PASSWORD: changeme
